dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
