dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts@4.7.3
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  development:
    vrf_coordinator:
      gas_limit: 100000
      keyhash: '0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15'
  goerli:
    eth_usd_price_feed:
      address: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    vrf_coordinator:
      address: '0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D'
      gas_limit: 100000
      keyhash: '0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15'
    link_token:
      address: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    verify: True
  mainnet-fork:
    eth_usd_price_feed:
      address: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
