dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
dotenv: .env
networks:
  default: ganache-local
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
  ganache-local:
    verify: false
wallets:
  from_key: ${PRIVATE_KEY}
